spring.application.name=chatMantisBT

# Redis Configuration (Redis Cloud)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=${REDIS_TIMEOUT}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED}

# Lettuce pool configuration
spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE}
spring.data.redis.lettuce.pool.max-idle=${REDIS_POOL_MAX_IDLE}
spring.data.redis.lettuce.pool.min-idle=${REDIS_POOL_MIN_IDLE}
spring.data.redis.lettuce.pool.max-wait=${REDIS_POOL_MAX_WAIT}

# Redis repositories
spring.data.redis.repositories.enabled=${REDIS_REPOSITORIES_ENABLED: false}

# Supabase PostgreSQL Configuration
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=${POSTGRES_DRIVER}

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true